# Generated by Django 3.2.5 on 2021-07-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='postCodeOrganization',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Индекс организации'),
        ),
    ]
