# Generated by Django 3.2.5 on 2021-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='postCodeOrganization',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название организации'),
        ),
    ]
