# Generated by Django 3.2.3 on 2021-05-26 18:46

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_auto_20210520_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='salaryPerHour',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='ИНН должен содержать только цифры')], verbose_name='Заработная плата в час'),
        ),
    ]
