# Generated by Django 3.2.4 on 2021-06-30 09:47

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_tariff_kitchenorhall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='cityName',
            field=models.CharField(max_length=150, verbose_name='Название города'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='salaryPerHour',
            field=models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='ИНН должен содержать только цифры')], verbose_name='Заработная плата ₽ в час'),
        ),
    ]
