# Generated by Django 3.2.5 on 2021-07-19 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPatentIssue', models.DateField(verbose_name='Дата выдачи патента')),
                ('dateExpirationPatent', models.DateField(verbose_name='Дата окончания патента')),
                ('patentIssuedBy', models.TextField(blank=True, null=True, verbose_name='Кем выдан патент')),
                ('patentSeries', models.CharField(max_length=15, verbose_name='Серия патента')),
                ('patentNumber', models.CharField(max_length=12, verbose_name='Номер патента')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='ФИО сотрудника')),
            ],
            options={
                'verbose_name': 'Патент',
                'verbose_name_plural': 'Патенты',
            },
        ),
        migrations.CreateModel(
            name='PatentPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentTermFrom', models.DateField(verbose_name='Срок оплаты патента от')),
                ('paymentTermUntil', models.DateField(verbose_name='Срок оплаты патента до')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.patent', verbose_name='Оплаченный патент')),
            ],
            options={
                'verbose_name': 'Квитанция оплаты патента',
                'verbose_name_plural': 'Квитанции оплаты патентов',
            },
        ),
    ]
