# Generated by Django 3.2.3 on 2021-05-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfPatentIssue', models.DateField(verbose_name='Дата выдачи патента')),
                ('dateExpirationPatent', models.DateField(verbose_name='Дата окончания патента')),
                ('deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='ФИО сотрудника')),
            ],
            options={
                'verbose_name': 'Патент',
                'verbose_name_plural': 'Патенты',
            },
        ),
        migrations.CreateModel(
            name='PatentPaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentTermFrom', models.DateField(verbose_name='Срок оплаты патента от')),
                ('paymentTermUntil', models.DateField(verbose_name='Срок оплаты патента до')),
                ('patent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patents.patent', verbose_name='Информация о патенте')),
            ],
            options={
                'verbose_name': 'Квитанция оплаты патента',
                'verbose_name_plural': 'Квитанции оплаты патентов',
            },
        ),
    ]
