# Generated by Django 3.2.5 on 2021-07-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='patentIssuedBy',
            field=models.TextField(blank=True, default='', verbose_name='Кем выдан патент'),
        ),
    ]
