# Generated by Django 3.2.5 on 2021-07-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinorganization',
            name='reasonWorkEmployee',
            field=models.CharField(blank=True, choices=[('P', 'Патент'), ('EAEU', 'ЕАЭС'), ('S', 'Обучение в России')], max_length=120, null=True, verbose_name='Основание работы сотрудника'),
        ),
    ]
