# Generated by Django 3.2.3 on 2021-05-26 18:46

import datetime
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='INN',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(limit_value=12, message='ИНН не может состоят из менее чем 12 цифр'), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='ИНН должен содержать только цифры')], verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='SNILS',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(limit_value=11, message='СНИЛС не может состоят из менее чем 11 цифр'), django.core.validators.RegexValidator(re.compile('^\\d+(?:\\d+)*\\Z'), code='invalid', message='СНИЛС должен содержать только цифры')], verbose_name='СНИЛС'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birthday',
            field=models.DateField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.date.today, message='Дата рождения не может превышать сегодняшнюю')], verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='citizenship',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(code=None, flags=0, inverse_match=None, message='Название страны содержить только буквы', regex='^[a-zA-Zа-яА-ЯёЁ ]+$')], verbose_name='Гражданство'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullName',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(code=None, flags=0, inverse_match=None, message='ФИО должно содержать только буквы', regex='^[a-zA-Zа-яА-ЯёЁ -]+$')], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fullNameInGenetive',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(code=None, flags=0, inverse_match=None, message='ФИО должно содержать только буквы', regex='^[a-zA-Zа-яА-ЯёЁ -]+$')], verbose_name='Родительный падеж ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passportNumber',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\ \\d+)*\\Z'), code='invalid', message='Неправильный вид номера паспорта')], verbose_name='Номер паспорта'),
        ),
    ]
