# Generated by Django 3.2.5 on 2021-07-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210724_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='nameMIA',
            field=models.CharField(blank=True, max_length=240, verbose_name='Название МВД'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passportNumber',
            field=models.CharField(max_length=10, verbose_name='Номер паспорта'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passportSeries',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Серия паспорта'),
        ),
    ]
