# Generated by Django 3.2.5 on 2021-07-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210724_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinorganization',
            name='reasonWorkEmployee',
            field=models.CharField(choices=[('P', 'Патент'), ('EAEU', 'ЕАЭС'), ('S', 'Другое')], max_length=120, verbose_name='Основание работы сотрудника'),
        ),
    ]
