# Generated by Django 3.2.7 on 2021-09-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_employeeinorganization_reasonworkemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bankDetailsBIC',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='БИК'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankDetailsNameBank',
            field=models.CharField(default='', max_length=500, verbose_name='Название банка'),
        ),
        migrations.AddField(
            model_name='employee',
            name='bankDetailsPaymentAccount',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Расчетный счет'),
        ),
    ]
