# Generated by Django 3.2.8 on 2021-10-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20210930_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='birthplace',
        ),
        migrations.AddField(
            model_name='employee',
            name='birthplace_city',
            field=models.CharField(blank=True, max_length=120, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthplace_country',
            field=models.CharField(blank=True, max_length=120, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthplace_home',
            field=models.CharField(blank=True, max_length=120, verbose_name='Дом'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthplace_home_expansion',
            field=models.CharField(blank=True, max_length=120, verbose_name='Расширение дома (корпус, строение, подъезд, этаж, квартира, офис,..).'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthplace_locality',
            field=models.CharField(blank=True, max_length=120, verbose_name='Населенный пункт'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthplace_street',
            field=models.CharField(blank=True, max_length=120, verbose_name='Улица'),
        ),
        migrations.AddField(
            model_name='employee',
            name='birthplace_subject',
            field=models.CharField(blank=True, max_length=120, verbose_name='Субъект (край, область и т.д.)'),
        ),
        migrations.AlterField(
            model_name='employeeinorganization',
            name='admissionOrderNumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Номер приказа о приёме'),
        ),
    ]
