# Generated by Django 3.2.13 on 2022-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20220505_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлён'),
        ),
    ]
