# Generated by Django 3.2.13 on 2022-06-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employee_namemia'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeinorganization',
            name='accessDate',
            field=models.DateField(blank=True, null=True, verbose_name='Дата доступа в ресторан (сопроводительное)'),
        ),
    ]
